### ISSUE TITLE
O script não funciona mais 

### ISSUE THREAD

**Issue by Umguyaleatorio** [euyogi/Prototipo-YogiNotificadorFruta#1]
Dps da atualização do blox fruits,o script se quer inicia ou faz algo, não notifica, não fala o nome,nem aparece nas opções o ligar/desligar

Se poder fazer uma versão mais atualizada ficaria agradecido

**Comment by euyogi** [comment]
Opa, estou dando uma olhada aqui, arrumei a interface não aparecendo, mas ainda to vendo se ainda está localizando as frutas

**Comment by euyogi** [comment]
Testei rapidinho aqui e encontrei uma diamante e uma luz, parece que tá funcionando agora
